events {}

http {
    geo $is_ru {
    default 0;              # ← Все IP, которых нет ниже: 0 = РАЗРЕШИТЬ
    127.0.0.1 1;            # ← IPv4 localhost <- main
    ::1 1;                  # ← IPv6 localhost
    5.3.0.0/16 1;           # ← Российский диапазон (85 000+ IP)
    31.13.64.0/19 1;        # ← Российский диапазон
    77.88.0.0/18 1;         # ← Яндекс (4 000+ IP)
    95.108.128.0/17 1;      # ← Яндекс (32 000+ IP)
}

    server {
        listen 80;
        location = /blocked {
            internal;
            root html;
            try_files /blocked.html =404;
        }
        location / {
            if ($is_ru = 1) {
                return 302 /blocked;
            }
            proxy_pass http://127.0.0.1:8080;
        }
    }
}
